### ISSUE TITLE
Terms from the ECO are not accessible

### ISSUE THREAD

**Issue by cpauvert** [OntoZoo/ontobee#174]
Hi all,
The terms from the Evidence and Conclusion Ontology are sadly not accessible from Ontobee despite the ontology being in the dropdown menu. Purl links return the ["Term not found" page](https://www.ontobee.org/ontology/ECO?iri=https://purl.obolibrary.org/obo/ECO_0007661) and a [keyword search](https://www.ontobee.org/search?ontology=ECO&keywords=computational+evidence&submit=Search+terms) returns no terms.

The purl links were obtained either from [the ECO browser](https://evidenceontology.org/browse/#ECO_0007661) and a [term search](https://www.ebi.ac.uk/ols/search?q=COMBINATORIAL+COMPUTATIONAL+AND+EXPERIMENTAL+EVIDENCE) on the OLS.

Should this be mentioned to the ECO team instead?
Best,

**Comment by yongqunh** [comment]
This should be fixed now:
https://www.ontobee.org/ontology/ECO
thanks,
Oliver

**Comment by cpauvert** [comment]
Hi Oliver, 
Thanks for your effort! While the link you provided work indeed, there is still an issue with known terms from the ECO that are not accessible. For instance, https://www.ontobee.org/ontology/ECO?iri=https://purl.obolibrary.org/obo/ECO_0007661 still throws a "Term not Found" page despite being a term of the ECO. Even searching the term in ontobee is not successful.
Best,

**Comment by yongqunh** [comment]
Interesting, this works:
https://www.ontobee.org/ontology/ECO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0007661

**Comment by yongqunh** [comment]
https://www.ontobee.org/ontology/ECO?iri=http://purl.obolibrary.org/obo/ECO_0007661
also works for me.

**Comment by yongqunh** [comment]
The difference is:
iri=https://purl.obolibrary.org/obo/ECO_0007661
vs:
iri=http://purl.obolibrary.org/obo/ECO_0007661

**Comment by nsuvarnaiari** [comment]
The only difference I see is the http purls working but not https.(sorry reading @yongqunh latest message now).

**Comment by cpauvert** [comment]
The devil is in the details! thanks for spotting this @yongqunh I can access the pages on ontobee now. Thanks @nsuvarnaiari I also saw that the URL on the ECO browser were using http instead of https!
Best,
