### ISSUE TITLE
Many ontologies are massively out of date

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#51]
http://sparql.hegroup.org/sparql?default-graph-uri=&query=SELECT+*+WHERE+{%3Fx+owl%3AversionIRI+%3Fy}&format=text%2Fhtml&debug=on&timeout=

Just eyeballing the list I can see many of these ontologies have had many intermediate releases. In some cases the diff between the versionIRI on the purl and that on ontobee is 2 years. It should be trivial to check by wgetting the purl and examining the versionIRI, but at a glance at least:

 * ma
 * ncbitaxon
 * uberon #50
 * vto #49 
 * ro
 * cl
 * go
 * zfs 
 * wbbt
 * envo
 * po

many more

**Comment by yongqunh** [comment]
We are working on updating these ontologies now.
In addition, we are updating our program to make the updating more automatic.
Thanks,
Oliver

**Comment by cmungall** [comment]
Any update on this?

**Comment by ontoden** [comment]
Some of the listed ontologies have been updated manually.

We are currently updating our automatic program to ensure automatic updating.

Thanks,

Oliver

**Comment by yongqunh** [comment]
All these ontologies have been updated and resolved in Ontobee.
Edison in my lab has done a good amount of work to solve several related issues.
Please check them out and let us know if you found any additional problem.
Thanks,
Oliver

**Comment by cmungall** [comment]
It's looking a lot better, but some issues still remain.

For example, if you do the sparql query, you'll see
```
http://purl.obolibrary.org/obo/fypo.owl 	http://purl.obolibrary.org/obo/fypo/releases/2013-10-16/fypo.owl
```

However:
```
$ curl -L http://purl.obolibrary.org/obo/fypo.owl  | grep versionIRI
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/fypo/releases/2015-06-12/fypo.owl"/>
```

**Comment by yongqunh** [comment]
We should have solved the issues related to these ontologies now. Please check out.

Later we will develop a program to automatically check for updates.

Edison & Oliver

**Comment by cmungall** [comment]
Thanks!
